spring:
  application:
    name: ui
  http:
    encoding:
      charset: UTF-8
  # mysql\u8FDE\u63A5\u6C60\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.171.230:3306/tx_order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall
    druid:
      initial-size: 5 #\u521D\u59CB\u5316\u8FDE\u63A5\u5927\u5C0F
      min-idle: 5 #\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      max-active: 10 #\u6700\u5927\u8FDE\u63A5\u6570
      query-timeout: 6000 #\u67E5\u8BE2\u8D85\u65F6\u65F6\u95F4
      transaction-query-timeout: 6000 #\u4E8B\u52A1\u67E5\u8BE2\u8D85\u65F6\u65F6\u95F4
      remove-abandoned-timeout: 1800 #\u5173\u95ED\u7A7A\u95F2\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
  # redis连接配置
  redis:
    host: 47.104.171.230           # redis主机地址
    port: 6379                   # redis主机端口
    database: 1                  # Redis数据库索引（默认为0）
    password:                     # redis链接密码
    lettuce:
      pool:
        max-active: 20     # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms       # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        # 连接池中的最大空闲连接
        min-idle: 0        # 连接池中的最小空闲连接
    timeout: 5000ms
  rabbitmq:
    host: 47.104.171.230
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 10000
    template:
      mandatory: true
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调

server:
  port: 8001
  tomcat.max-threads: 800
  tomcat.uri-encoding: UTF-8

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false #\u662F\u5426\u5F00\u542F\u964D\u7EA7\u8D85\u65F6
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000 #\u8D85\u65F6\u6B64\u65F6\u95F4\uFF0C\u670D\u52A1\u964D\u7EA7

ribbon:
  ReadTimeout: 60000 #\u8BFB\u53D6\u6570\u636E\u8D85\u65F6
  ConnectTimeout: 60000 #\u8FDE\u63A5\u8D85\u65F6
  OkToRetryOnAllOperations: false #\u662F\u5426\u91CD\u8BD5
  MaxAutoRetriesNextServer: 0

eureka:
  instance:
    hostname: ${spring.cloud.client.hostname}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 10 # \u62C9\u53D6\u670D\u52A1\u6CE8\u518C\u72B6\u6001\u65F6\u95F4\u95F4\u9694\uFF0C\u9ED8\u8BA4\u4E3A30\u79D2

#\u5FAE\u670D\u52A1\u5E95\u5C42\u670D\u52A1\u540D\u79F0
order-server-name: order
stock-server-name: stock
